triggers:
  - type: meya.regex
    properties:
        ignorecase: true
        pattern: الفلبينية
        capture_text: true
name: Alfilipinya
states:
    First:
        component: meya.text
        properties:
            text: "هل تفضل أن تكون جلسة التنظيف صباحاً أو بعد الظهر ؟"