triggers:
  - type: meya.regex
    properties:
        ignorecase: true
        pattern: Booking
        capture_text: true
name: Booking
states:
    First:
        component: meya.text
        properties:
            text: Are you interested in booking a single visit or a package ?
        return: true    
    Handover:
        component: meya.text
        properties:
            text: Ok, meanwhile I will connect you to one of my colleagues.