triggers:
  - type: meya.catchall
name: CatchAll
states:
    text_buttons_state:
        component: meya.text_buttons
        properties:
            text: "I'm sorry I didn't understand what you mean exactly, please help me better understand what you need, does it have to do with:"
            output: button_click
            buttons:
                - text: Booking
                  action: next
                  flow: Booking 
                  data:
                    foo: bar
                - text: Rescheduling
                  action: next
                  flow: Booking
                - text: Information
                  action: next
                  flow: ToCancel
                - text: Payment
                  action: next
                  flow: ToCancel
                - text: Cancellation
                  action: next
                  flow: ToCancel
                - text: Making a complaint
                  action: next
                  flow: IsLate
        delay:
            relative: 5