triggers:
  - type: meya.catchall
    properties:
        detect_language: false
        include_non_text_events: false
name: CatchAll
states:
    First:
        component: meya.text
        properties:
            text: هل تفضل اللغة العربية أم الإنكليزية؟