triggers:
  - type: meya.regex
    properties:
        ignorecase: true
        pattern: cleaning tools
        capture_text: true
name: CleaningTools
states:
    text_buttons_state:
        component: meya.text
        properties:
            text: "I'm sorry, we currently don't provide cleaning tools in your area"
        delay:
            relative: 5