triggers:
  - type: meya.regex
    properties:
        ignorecase: true
        pattern: expensive
        capture_text: true
name: expensive
states:
    first:
        component: meya.text
        properties:
            text: We provide high quality cleaning services and 24 hour customer support! We also help you build your schedule with your favorite service provider group and offer regular discounts for returning customers