triggers:
  - type: meya.regex
    properties:
        ignorecase: true
        pattern: filipino
        capture_text: true
name: Filipino
states:
    First:
        component: meya.text
        properties:
            text: Do you prefer the cleaning session to be at morning or afternoon ?