triggers:
  - type: meya.regex
    properties:
        ignorecase: true
        pattern: ما هو ماتيك
        capture_text: true
name: MaHouwaMatic
states:
    first:
        component: meya.text
        properties:
            text: ماتك هي منصة للخدمات المنزلية تصلك بمختصين بالتنظيف عن طريق بضع نقرات
