triggers:
  - type: meya.regex
    properties:
        ignorecase: true
        pattern: ماذا يتضمن التنظيف
        capture_text: true
name: MazaYataDamanAlTanzif
states:
    first:
        component: meya.text
        properties:
            text: تتضمن خدماتنا تنظيف الغبار والمسح والتنظيف بالمكنسة الكهربائية للغرف والحمامات. يمكنك إضافة طلبات خاصة حسب حاجات منزلك
