triggers:
  - type: meya.regex
    properties:
        ignorecase: true
        pattern: أريد أن احجز
        capture_text: true
name: ouridou2anA7ajouza
states:
    first:
        component: meya.text
        properties:
            text: سأحتاج إلى بعض التفاصيل لإكمال هذا الحجز. هل استطيع الحصول على اسمك الكامل وعنوانك ورقم هاتفك المحمول وعنوان بريدك الإلكتروني ، من فضلك؟
    text_buttons_state:
        component: meya.text_buttons
        properties:
            text: Your text here
            output: button_click
            buttons:
                - text: button_1
                  action: next
                  data:
                    foo: bar
                - text: button_2
                  action: next
    next_state:
        component: meya.text
        properties:
            text: You clicked {{ flow.button_click }}