triggers:
  - type: meya.regex
    properties:
        ignorecase: true
        pattern: referral
        capture_text: true
name: referral
states:
    first:
        component: meya.text
        properties:
            text: You may share a referral code with family or friends from the free cleanings page. After the referred person completes a visit with us, you will both receive 50% off your booking.