triggers:
  - type: meya.regex
    properties:
        ignorecase: true
        pattern: Rescheduling
        capture_text: true
name: Rescheduling
states:
    First:
        component: meya.text
        properties:
            text: Ok, meanwhile I will connect you to one of my colleagues.