triggers:
  - type: meya.start_chat
name: StartChat
states:
    First:
        component: meya.text_buttons
        properties:
            text: Hello welcome to Matic and thank you for contacting us. Please specify the area you belong to; if its not in the list below then hopefully we will cover it soon.
            output: button_click
            buttons:
                - text: Riyadh
                  action: next
                  scope: user
                  key: location
                  data:
                    foo: bar
                - text: Dammam
                  action: next
                  flow: Package
                - text: Alkhobar
                  action: next
                - text: Dharan
                  action: next
                - text: Hasa
                  action: next
                - text: Hofuf
                  action: next
                - text: Jeddah
                  action: next
                - text: Dubai
                  action: next
        delay:
            relative: 5
    Second:
        component: meya.text_buttons
        properties:
            text: "That's great! how can I help you today?"
            output: button_click
            buttons:
                - text: Booking
                  action: next
                  flow: Booking 
                  data:
                    foo: bar
                - text: Rescheduling
                  action: next
                  flow: Booking
                - text: Information
                  action: next
                  flow: ToCancel
                - text: Payment
                  action: next
                  flow: ToCancel
                - text: Cancellation
                  action: next
                  flow: ToCancel
                - text: Making a complaint
                  action: next
                  flow: IsLate
        delay:
            relative: 10