triggers:
  - type: meya.wit
    properties:
        min_confidence: '0.8'
        token: JDPWO6HXXX4MFRH2YIVDVKGEEGQMPW7H
name: TestWit
route: true
states:
    booking:
        component: meya.text
        properties:
            text: booking test
        return: true
    Garbage:
        component: meya.text
        properties:
            text: Garbage
        return: true
    WhatIsMatic:
        component: meya.text
        properties:
            text: Matic is a platform for home services that connects you with cleaning professionals in a few clicks.
        return: true
    CoveredArea:
        component: meya.text
        properties:
            text: Thank you for contacting us, please specify the area you wish the cleaning session to be in to make sure you are covered
        return: true
    Transportation:
        component: meya.text
        properties:
            text: Thanks for your concern, Matic wants to make the cleaning process easy for you therefor we take full care of the transportation.
        return: true
    AppUse:
        component: meya.text
        properties:
            text: With Matic Services, booking a trusted housekeeper in Dubai, Riyadh, Jeddah and Dammam has never been easier schedule your Matic home professional at the push of a button.
        return: true
    AppError:
        component: meya.text
        properties:
            text: Can I know what's the exact error? I will also need your mobile number to check your details. In the meantime, can you please check if the app needs to be updated?
        return: true
    Payment:
        component: meya.text
        properties:
            text: You can only pay by card or you can transfer the payment to our bank account
        return: true
    Nationalities:
        component: meya.text
        properties:
            text: "Our service providers are professional of different Nationalities depending on your area and your suitable time, we have: Filippinos, Indonesians, Neppal, Nigerian, Ugandan"
        return: true
    AppLanguageChange:
        component: meya.text
        properties:
            text: You may change the language in the application, if you need help please let us know
        return: true
    BabySitter:
        component: meya.text
        properties:
            text: We curretnly don't provide Babysitter services
        return: true
    ServicesInclude:
        component: meya.text
        properties:
            text: Our cleaning services include dusting, wiping, vacuum cleaning rooms and bathrooms. You can add specific requests based on your home's needs!
            action: next
        delay:
            relative: 5
        transitions: 
            next: ServicesInclude1
    ServicesInclude1:
        component: meya.text
        properties:
            text: We provide high quality cleaning services and 24 hour customer support! We also help you build your schedule with your favorite cleaner.
        delay:
            relative: 5
        return: true
    CancellationFees:
        component: meya.text
        properties:
            text: Cancellation charges only apply if you cancel your session less than 24 hours before your cleaning session. Fees will be 100% of your total cleaning session. Otherwise, no cancellation fees will be incurred.
        delay:
            relative: 5
        return: true
    IroningServices:
        component: meya.text
        properties:
            text: We curretnly don’t provide Ironing Services
        delay:
            relative: 5
        return: true
    LegalService:
        component: meya.text
        properties:
            text: All the service providers working with us are legal employees authorized to perform part time home cleaning.
        delay:
            relative: 5
        return: true
    Bookink2SPS:
        component: meya.text
        properties:
            text: Booking more than a cleaner at the same time is possible, one of our specialists will check the availability and gets back to you shortly
        delay:
            relative: 5
        return: true
    Location:
        component: meya.text
        properties:
            text: "our main location is in Dubai but our offices in KSA are located in Dammam Al Waha - Bader offices https://maps.google.com/?q=24.747698,46.619045"
        delay:
            relative: 5
        return: true
    FemaleCleaners:
        component: meya.text
        properties:
            text: Our cleaners are professional females
        delay:
            relative: 5
        return: true
    SameCleaner:
        component: meya.text
        properties:
            text: We might not be able to find you the same cleaner, however help us understand what do you need the cleaner to de specifically so that we find your match. Meanwhile one of of our specialists will check her availability.
        delay:
            relative: 5
        return: true
    PestControl:
        component: meya.text
        properties:
            text: We currently don't have pest control services, Our cleaning services include dusting, wiping, vacuum cleaning rooms and bathrooms.
        delay:
            relative: 5
        return: true
    PermanentCleaner:
        component: meya.text
        properties:
            text: We are sorry but our cleaners perform part time cleaning jobs and can’t stay over your house, however you can pick the cleaner that you preffer and have her visit you daily for 6 hours.
        delay:
            relative: 5
        return: true
    FridayBooking:
        component: meya.text
        properties:
            text: Thank you for choosing Matic, we currently don't provide our services on Friday, would you like me to check the availability for a different day?
        delay:
            relative: 5
        return: true
    PreferredSP:
        component: meya.text
        properties:
            text: It's great that you were able to find the cleaner that matches the needs of your house, help us know what made her be your preferred cleaner. In the mean time, one of our specialists will check her availability and gets back to you.
        delay:
            relative: 5
        return: true
    Refund:
        component: meya.text
        properties:
            text: Thank you for raising this, we will escalate this to the specialized department and they will check the refund case and contact you back. Thank you for your patience.
        delay:
            relative: 5
        return: true
    ambiguous_state:
        component: meya.text
        properties:
            text: ambiguous_state
        return: true