triggers:
  - type: meya.regex
    properties:
        ignorecase: true
        pattern: three times a week
        capture_text: true
name: ThreeTimesAWeek
states:
    First:
        component: human.transfer
        properties:
            text: Ok, meanwhile I will connect you to one of my colleagues.
        assignee: "Homer"
        note: |
            send msg to homer