triggers:
  - type: meya.regex
    properties:
        ignorecase: true
        pattern: want a cleaner
        capture_text: true
name: wantacleaner
states:
    first:
        component: meya.text
        properties:
            text: I will need a few details to complete this booking.May I have your complete name, address, mobile number and email address, please?
    text_buttons_state:
        component: meya.text_buttons
        properties:
            text: Your text here
            output: button_click
            buttons:
                - text: button_1
                  action: next
                  data:
                    foo: bar
                - text: button_2
                  action: next
    next_state:
        component: meya.text
        properties:
            text: You clicked {{ flow.button_click }}