triggers:
  - type: meya.regex
    properties:
        ignorecase: true
        pattern: want to complain
        capture_text: true
name: wanttocomplain
states:
    first:
        component: meya.text
        properties:
            text: I apologize again for any inconvenience this may have caused. We are working on this and put this on highest priority! Please give me a few more minutes to check on the status of your complaint.