triggers:
  - type: meya.regex
    properties:
        ignorecase: true
        pattern: what is matic
        capture_text: true
name: whatismatic
states:
    first:
        component: meya.text
        properties:
            text: Matic is a platform for home services that connects you with cleaning professionals in a few clicks.

